import "../globals.css";
import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import { Header } from "../_components/Header";

const roboto_slab = Titillium_Web({
  weight: ["200", "300", "400", "600", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto_slab.className + " h-screen"}>
        <Header />
        {children}
      </body>
    </html>
  );
}
